DROP DATABASE IF EXISTS myDatabase;

CREATE DATABASE myDatabase;

USE myDatabase;

DROP TABLE IF EXISTS rooms;

CREATE TABLE rooms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  roomName VARCHAR(255),
  roomSqft INT
);

DROP TABLE IF EXISTS items;

CREATE TABLE items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  width INT,
  height INT,
  roomId INT,
  isPaintable BOOLEAN,
  FOREIGN KEY (roomId) REFERENCES rooms(id) ON DELETE CASCADE ON UPDATE CASCADE
);
